[directory]
truncation_length = 5
truncate_to_repo = false

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 24
truncation_symbol = ""

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[git_status]
conflicted = "ğŸ³"
ahead = " â® "
behind = " â© "
diverged = " ğŸ”€ "
untracked = " â—"
stashed = " ğŸ“¥ "
modified = " ğŸ“ "
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "ğŸ‘… "
deleted = " ğŸ—‘ "

[character]
symbol = "Î»"
error_symbol = "âœ—"
use_symbol_for_status = true

[aws]
disabled = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"
disabled = false

[[battery.display]]
threshold = 50
style = "bold red"

[python]
prefix = ""
